In [4]:
# Importing the Required Libraries
import numpy as np

# Displaying the Original Data
X = np.array([[2, 5],
              [6, 4],
              [10, 11],
              [14, 14]])
print("Original Data:\n", X)

# Calculating the Mean of each Feature and Stardardizing the Data
mean = np.mean(X, axis=0)
print("\nMean of each feature:", mean)

# Centering the Data
X_centered = X - mean
print("\nCentered Data:\n", X_centered)

# Calculating the Covariance Matrix
cov_matrix = np.cov(X_centered.T)
print("\nCovariance Matrix:\n", cov_matrix)

# Computing Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Sorting the Eigenvalues and Eigenvectors
sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]
print("\nSorted Eigenvalues:\n", sorted_eigenvalues)
print("\nSorted Eigenvectors:\n", sorted_eigenvectors)

# Projecting Data onto the Principal Component
principal_component = sorted_eigenvectors[:, 0]
print("\nPrincipal Component (first eigenvector):\n", principal_component)

# Projecting the Data
X_projected = X_centered.dot(principal_component)
print("\nProjected Data:\n", X_projected)

Original Data:
 [[ 2  5]
 [ 6  4]
 [10 11]
 [14 14]]

Mean of each feature: [8.  8.5]

Centered Data:
 [[-6.  -3.5]
 [-2.  -4.5]
 [ 2.   2.5]
 [ 6.   5.5]]

Covariance Matrix:
 [[26.66666667 22.66666667]
 [22.66666667 23.        ]]

Eigenvalues:
 [47.57402129  2.09264537]

Eigenvectors:
 [[ 0.73505751 -0.67800476]
 [ 0.67800476  0.73505751]]

Sorted Eigenvalues:
 [47.57402129  2.09264537]

Sorted Eigenvectors:
 [[ 0.73505751 -0.67800476]
 [ 0.67800476  0.73505751]]

Principal Component (first eigenvector):
 [0.73505751 0.67800476]

Projected Data:
 [-6.78336172 -4.52113645  3.16512693  8.13937125]
